### ISSUE TITLE
Could not load thumbnail

### ISSUE THREAD

**Issue by modem7** [ex0nuss/Plex-Export-Docker#3]
Heya, 

When I start this container, I get a lot of errors with "could not load thumbnail". 

I've checked the token, but still no go.

What would you suggest?

**Comment by ex0nuss** [comment]
Hi there,

thx for opening up this issue. Checking the token is a great first troubleshooting step!

### Which PLEX_URL do you use to access your Plex media server?
In theory there are there options:
1. Using localhost (e.g. http://localhost:32400): Not usable because we are running Plex-Export in a docker container
2. Using a local ip (e.g. http://192.168.1.100:32400): I am using that options for my PLEX_URL. It works really reliable and great.
3. Using a remote address (e.g. https://plex.domain.com)

### Please check that you have an network connection to the plex server via the PLEX_URL

### How did you obtain the access token? 
It's recommended to get the token via the PLEX_URL address.
E.g.: When you use a local ip (recommended), you should also get the token via your local ip address.

It would be also nice if you add more details / logs :)

**Comment by modem7** [comment]
Heya,

This is my compose file:

```yaml
  development-plexexport-php:
    image: plexexport/test:latest
    container_name: frontend-plexexport-php
    restart: unless-stopped
    volumes:
      - $USERDIR/PlexExport:/data
    environment:
      - PLEX_URL=http://192.168.0.254:32400
      - PLEX_SECTIONS=Movies
      - PLEX_TOKEN=<token>
      - PLEX_INTERVAL=360m
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "4"

  development-plexexport-nginx:
    image: nginx:mainline-alpine
    container_name: frontend-plexexport-nginx
    restart: unless-stopped
    ports:
      - 9999:80
    volumes:
      - $USERDIR/PlexExport:/data
      - $USERDIR/PlexExport/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - development-plexexport-php
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "4"
```

Here's the start and end of the logs:

```Verilog
2021-09-20T16:05:57.731059602Z Sleeps for 15s to initialize
2021-09-20T16:06:12.749695826Z 16:06:12 Welcome to the Plex Exporter v1
2021-09-20T16:06:12.749731984Z 16:06:12 Searching for sections in the Plex library at http://192.168.0.254:32400/
2021-09-20T16:06:12.756691122Z 16:06:12 Found 7 sections in this Plex library
2021-09-20T16:06:12.756789346Z 16:06:12 Scanning section: Movies
2021-09-20T16:06:13.723044178Z 16:06:13 Found 839 movies in Movies
2021-09-20T16:06:13.723107552Z 16:06:13 Scanning movie: *batteries not included
2021-09-20T16:06:13.725424965Z 16:06:13 Error: Could not load thumbnail for *batteries not included
~~~~~~~
today at 17:10:07 16:10:07 Error: Undefined array key "Family" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Comedy" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Fantasy" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Science Fiction" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Thriller" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Action" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Horror" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Drama" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Crime" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "War" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "History" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Animation" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Adventure" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Mystery" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Romance" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Musical" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Music" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Biography" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Western" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Suspense" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "TV Movie" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Sport" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Children" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Short" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Martial Arts" on line 154
today at 17:10:07 16:10:07 Error: Undefined array key "Documentary" on line 154
today at 17:10:07 16:10:07 Added 839 items from the Movies section
today at 17:10:07 16:10:07 Exporting data for 1 section containing 839 items
today at 17:10:07 16:10:07 Generating and minifying JSON output, this may take some time...
today at 17:10:07 16:10:07 Wrote 1375350 bytes to /app/plex-data/data.js
today at 17:10:07 16:10:07 Plex Export completed in 31.22 seconds
today at 17:10:07
today at 17:10:07 Copping app-files to /data
today at 17:10:07 ash: /data/index.html: unknown operand
today at 17:10:07 Chmoding /data
today at 17:10:07
today at 17:10:07 Sleep until next run in 360m
```

I'm currently using local access, and the token from local access as well.

I've also attempted to attach the container to the same network as plex, but still same issues unfortunately! 

Just as an addendum, I'm using the new plex movie agent that was introduced quite a while back which I think changed the API locations.
